language: csharp
mono: none
sudo: required
dotnet: 5.0.13
branches:
  only:
    - master
script:
  - dotnet restore
  - dotnet build achihapi.sln
  - dotnet test ./test/hihapi.test/hihapi.test.csproj --filter DisplayName~hihapi.test.UnitTests
notifications:
  email:
    on_success: never
    on_failure: always