
DELETE FROM t_homedef WHERE ID IS NOT NULL;

DELETE FROM t_fin_account WHERE ID IS NOT NULL;
DELETE FROM [t_fin_account_ext_as] WHERE [ACCOUNTID] IS NOT NULL;
DELETE FROM [t_fin_account_ext_dp] WHERE [ACCOUNTID] IS NOT NULL;
DELETE FROM [t_fin_account_ext_loan] WHERE [ACCOUNTID] IS NOT NULL;
DELETE FROM [t_fin_asset_ctgy] WHERE [HID] IS NOT NULL;
DELETE FROM t_fin_controlcenter WHERE ID IS NOT NULL;
DELETE FROM t_fin_order WHERE ID IS NOT NULL;
DELETE FROM t_fin_document WHERE ID IS NOT NULL;
DELETE FROM t_fin_exrate WHERE TRANDATE IS NOT NULL;
DELETE FROM t_fin_setting WHERE SETID IS NOT NULL;
DELETE FROM t_fin_tmpdoc_dp WHERE DOCID IS NOT NULL;
DELETE FROM t_fin_tmpdoc_loan WHERE DOCID IS NOT NULL;


--DELETE FROM t_learn_award WHERE ID IS NOT NULL;
DELETE FROM t_learn_hist WHERE USERID IS NOT NULL;
DELETE FROM t_learn_obj WHERE ID IS NOT NULL;
--DELETE FROM t_learn_plan WHERE ID IS NOT NULL;

DELETE FROM [t_lib_book] WHERE [ID] IS NOT NULL;
DELETE FROM [t_lib_location] WHERE [ID] IS NOT NULL;
DELETE FROM [t_lib_location_detail] WHERE [ID] IS NOT NULL;
DELETE FROM [t_lib_book_ctgy] WHERE [ID] IS NOT NULL;
DELETE FROM [t_lib_person] WHERE [ID] IS NOT NULL;
