<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
	  <UserSecretsId>cf80adf9-ce70-4ce9-bb4e-a73887a492a6</UserSecretsId>
	  <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
    <Version>1.6.355</Version>
    <Authors>Alva Chien</Authors>
    <Product>H.I.H.</Product>
    <Copyright>© Alva Chien, 2019 - Present</Copyright>
    <PackageProjectUrl>https://github.com/alvachien/achihapi</PackageProjectUrl>
    <PackageLicenseUrl></PackageLicenseUrl>
    <Description>Web API for Home Info. Hub, built on OData and ASP.NET Core;</Description>
    <NeutralLanguage>en</NeutralLanguage>
    <RepositoryUrl>https://github.com/alvachien/achihapi</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="hihapi.unittest" />
    <InternalsVisibleTo Include="hihapi.integrationtest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.OData" Version="9.4.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.7" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>
</Project>
