-- Update Views: V_FIN_REPORT_BS
DROP VIEW IF EXISTS [dbo].[v_fin_report_bs]
GO

CREATE VIEW V_FIN_REPORT_BS
AS 
SELECT e.HID, e.ACCOUNTID, e.DEBIT_BALANCE, e.CREDIT_BALANCE, 
    e.DEBIT_BALANCE - e.CREDIT_BALANCE AS BALANCE
FROM (
    SELECT c.HID, 
        c.ACCOUNTID,
        c.DEBIT_BALANCE,
        CASE WHEN d.BALANCE_LC IS NULL THEN 0 ELSE -1 * d.BALANCE_LC END AS CREDIT_BALANCE
    FROM
    ( SELECT a.HID, a.ID AS ACCOUNTID, 
            CASE WHEN b.BALANCE_LC IS NULL THEN 0 ELSE b.BALANCE_LC END AS DEBIT_BALANCE
        FROM T_FIN_ACCOUNT as a 
        LEFT OUTER JOIN (SELECT HID, ACCOUNTID, BALANCE_LC FROM V_FIN_GRP_ACNT_TRANEXP WHERE TRANTYPE_EXP = 0) as b
			ON a.ID = b.ACCOUNTID AND a.HID = b.HID 
	) as c
	LEFT OUTER JOIN (SELECT HID, ACCOUNTID, BALANCE_LC FROM V_FIN_GRP_ACNT_TRANEXP WHERE TRANTYPE_EXP = 1) as d
		ON c.HID = d.HID AND c.ACCOUNTID = d.ACCOUNTID 
	) as e
GO

-- Update Views: V_FIN_REPORT_CC
DROP VIEW IF EXISTS [dbo].[v_fin_report_cc]
GO

create view [dbo].[v_fin_report_cc]
AS 
SELECT e.HID, e.CONTROLCENTERID, e.DEBIT_BALANCE, e.CREDIT_BALANCE, 
    e.DEBIT_BALANCE - e.CREDIT_BALANCE AS BALANCE
FROM (
    SELECT c.HID, 
        c.CONTROLCENTERID,
        c.DEBIT_BALANCE,
        CASE WHEN d.BALANCE_LC IS NULL THEN 0 ELSE -1 * d.BALANCE_LC END AS CREDIT_BALANCE
    FROM
    ( SELECT a.HID, a.ID AS CONTROLCENTERID, 
            CASE WHEN b.BALANCE_LC IS NULL THEN 0 ELSE b.BALANCE_LC END AS DEBIT_BALANCE
        FROM T_FIN_CONTROLCENTER as a 
        LEFT OUTER JOIN (SELECT HID, CONTROLCENTERID, BALANCE_LC FROM V_FIN_GRP_CC_TRANEXP WHERE TRANTYPE_EXP = 0) as b
			ON a.ID = b.CONTROLCENTERID AND a.HID = b.HID 
	) as c
	LEFT OUTER JOIN (SELECT HID, CONTROLCENTERID, BALANCE_LC FROM V_FIN_GRP_CC_TRANEXP WHERE TRANTYPE_EXP = 1) as d
		ON c.HID = d.HID AND c.CONTROLCENTERID = d.CONTROLCENTERID
	) as e
GO

-- Update Views:
DROP VIEW IF EXISTS v_fin_report_order
GO

CREATE VIEW v_fin_report_order
AS 
SELECT e.HID, e.ORDERID, e.DEBIT_BALANCE, e.CREDIT_BALANCE, 
    e.DEBIT_BALANCE - e.CREDIT_BALANCE AS BALANCE
FROM (
    SELECT c.HID, 
        c.ORDERID,
        c.DEBIT_BALANCE,
        CASE WHEN d.BALANCE_LC IS NULL THEN 0 ELSE -1 * d.BALANCE_LC END AS CREDIT_BALANCE
    FROM
    ( SELECT a.HID, a.ID AS ORDERID, 
            CASE WHEN b.BALANCE_LC IS NULL THEN 0 ELSE b.BALANCE_LC END AS DEBIT_BALANCE
        FROM T_FIN_ORDER as a 
        LEFT OUTER JOIN (SELECT HID, ORDERID, BALANCE_LC FROM v_fin_grp_order_tranexp WHERE TRANTYPE_EXP = 0) as b
			ON a.ID = b.ORDERID AND a.HID = b.HID 
	) as c
	LEFT OUTER JOIN (SELECT HID, ORDERID, BALANCE_LC FROM v_fin_grp_order_tranexp WHERE TRANTYPE_EXP = 1) as d
		ON c.HID = d.HID AND c.ORDERID = d.ORDERID
	) as e
GO

-- Set the version
INSERT INTO [dbo].[t_dbversion] ([VersionID],[ReleasedDate]) VALUES (14,'2020.03.15');

-- The end.
