<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
	  <IsPackable>false</IsPackable>
    <Version>1.5.215</Version>
    <Authors>Alva Chien</Authors>
    <Product>H.I.H.</Product>
    <Description>Home Info. Hub</Description>
    <Copyright>© Alva Chien, 2019 - Present </Copyright>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="coverlet.msbuild" Version="10.0.0">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.7" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit.v3" Version="3.1.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\hihapi\hihapi.csproj" />
    <ProjectReference Include="..\hihapi.test.common\hihapi.test.common.csproj" />
  </ItemGroup>

</Project>
